<dirac>
  <!-- Example: Using DIRAC variables to generate graph data -->
  <output>Generating graph data with Python...</output>
  
  <!-- Generate data using Python -->
  <python result="chartData">
import json
import math

# Generate some interesting data
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

# Simulate sales data with seasonal trend
sales_2025 = [50 + 30 * math.sin(i * math.pi / 6) + (i * 2) for i in range(12)]
sales_2026 = [60 + 35 * math.sin(i * math.pi / 6) + (i * 2.5) for i in range(12)]

# Round to integers
sales_2025 = [round(x) for x in sales_2025]
sales_2026 = [round(x) for x in sales_2026]

# Create JSON structure for Chart.js
data = {
    'labels': months,
    'datasets': [
        {
            'label': '2025 Sales',
            'data': sales_2025,
            'borderColor': '#667eea',
            'backgroundColor': 'rgba(102, 126, 234, 0.1)',
        },
        {
            'label': '2026 Sales',
            'data': sales_2026,
            'borderColor': '#764ba2',
            'backgroundColor': 'rgba(118, 75, 162, 0.1)',
        }
    ]
}

return json.dumps(data)
  </python>
  
  <output>Data generated! Opening graph...</output>
  
  <!-- Build the HTML with embedded data -->
  <python result="htmlContent">
import json

# Get the chart data we generated earlier
chart_data_json = globals().get('chartData', '{}')

html = f'''<html>
      <head>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
        <style>
          body {{
            font-family: Arial, sans-serif;
            padding: 40px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
          }}
          .container {{
            max-width: 1000px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 8px 32px rgba(0,0,0,0.3);
          }}
          h1 {{ 
            color: #333; 
            margin-bottom: 10px;
          }}
          .subtitle {{
            color: #666;
            margin-bottom: 30px;
          }}
          .info {{
            background: #f0f0f0;
            padding: 15px;
            border-radius: 8px;
            margin-top: 20px;
            font-size: 0.9em;
            color: #555;
          }}
        </style>
      </head>
      <body>
        <div class="container">
          <h1>📊 Sales Trend Analysis</h1>
          <p class="subtitle">Generated dynamically from Python data</p>
          <canvas id="chart"></canvas>
          
          <div class="info">
            <strong>💡 How this works:</strong><br>
            1. Python generates data using mathematical functions<br>
            2. Data is converted to JSON format<br>
            3. DIRAC passes the data to the browser<br>
            4. Chart.js renders the interactive graph
          </div>
        </div>
        
        <script>
          // This data was generated by Python in DIRAC!
          const chartData = {chart_data_json};
          
          new Chart(document.getElementById('chart'), {{
          new Chart(document.getElementById('chart'), {{
            type: 'line',
            data: chartData,
            options: {{
              responsive: true,
              plugins: {{
                legend: {{ position: 'top' }},
                title: {{
                  display: true,
                  text: 'Seasonal Sales Pattern with Growth Trend'
                }}
              }},
              scales: {{
                y: {{ 
                  beginAtZero: true,
                  title: {{
                    display: true,
                    text: 'Sales (in thousands)'
                  }}
                }},
                x: {{
                  title: {{
                    display: true,
                    text: 'Month'
                  }}
                }}
              }},
              interaction: {{
                mode: 'index',
                intersect: false
              }}
            }}
          }});
          
          console.log('Chart data from Python:', chartData);
        </script>
      </body>
    </html>'''

return html
  </python>
  
  <!-- Now display the generated HTML -->
  <browser title="Dynamic Graph from Python" port="3102"><variable name="htmlContent" /></browser>
  
  <output>✨ Graph opened at http://localhost:3102</output>
  <output>📈 Data was generated using Python with sine wave + linear growth!</output>
</dirac>
