<!-- Test: Show original LLM response before execution -->
<dirac>
  <output>Test LLM Original Response Display&#10;&#10;</output>
  
  <!-- Define some subroutines that LLM can use -->
  <subroutine name="greet" 
              param-name="string:required:Person's name"
              description="Greet a person by name">
    <output>Hello, <parameters select="@name" />!&#10;</output>
  </subroutine>
  
  <subroutine name="add"
              param-a="number:required:First number"
              param-b="number:required:Second number"
              description="Add two numbers">
    <eval name="sum">
      const a = parseFloat(getParams().attributes.a);
      const b = parseFloat(getParams().attributes.b);
      return a + b;
    </eval>
    <output>Sum: ${sum}&#10;</output>
  </subroutine>
  
  <output>Instructions:&#10;</output>
  <output>================&#10;&#10;</output>
  <output>When you use &lt;LLM execute="true"&gt;, you will now see TWO outputs:&#10;</output>
  <output>&#10;</output>
  <output>1. STDERR: [LLM Original Response] - The raw XML generated by the LLM&#10;</output>
  <output>2. STDOUT: The actual executed output from running that XML&#10;</output>
  <output>&#10;</output>
  <output>Example test (if you have LLM configured):&#10;</output>
  <output>&#10;</output>
  <output>Try running this example:&#10;</output>
  <output>  &lt;LLM execute="true"&gt;greet Alice&lt;/LLM&gt;&#10;</output>
  <output>&#10;</output>
  <output>You should see:&#10;</output>
  <output>  - In STDERR: [LLM Original Response] with the generated XML&#10;</output>
  <output>  - In STDOUT: "Hello, Alice!"&#10;</output>
  <output>&#10;</output>
  <output>This helps you understand what the LLM generated vs what was executed.&#10;</output>
  <output>&#10;</output>
  <output>Benefits:&#10;</output>
  <output>  - Debug LLM output quality&#10;</output>
  <output>  - See corrections/modifications before execution&#10;</output>
  <output>  - Verify LLM is generating correct Dirac XML&#10;</output>
  <output>  - Understand validation/correction pipeline&#10;</output>
</dirac>
